### ISSUE TITLE
Kloadgen components are not visible in JMeter

### ISSUE THREAD

**Issue by rathishks** [corunet/kloadgen#117] opened 2021-08-22 21:26 UTC
Built master branch (Java11) and copied the plugin jar to /bin/ext and restaretd JMeter. But the KLoadgen components are not visible in JMeter. Not sure what went wrong. Any suggestions?

**Comment by kszosze** [comment] 2021-08-23 14:40
Hi @rathishks,
the right folder is '/lib/ext' not '/bin/ext'. It should appear the components as we show in the README.md.

Do you mind double check on which folder you are dropping the jar?

Cheers!!

**Comment by M3lkior** [comment] 2021-08-31 09:08
hi @kszosze ; 

We also try to install KLoadGen on jMeter 5.4 ; building the master branch we deploy your plugin into `lib/ext` but the KLoadgen plugin don't appear in the plugin manager list 

![image](https://user-images.githubusercontent.com/5501911/131475301-09141744-7089-4dd2-8ea6-2b5f636713d3.png)

But the config components are available ... any idea ?

![image](https://user-images.githubusercontent.com/5501911/131475470-173cb93d-78b0-4e04-98ee-bfa256501baf.png)


Also, reproducible with the `3.0.0` tag

Thanks in advance

**Comment by M3lkior** [comment] 2021-08-31 13:18
ok @kszosze this about the name of you sample ;
@rathishks you should use the `Java Request`  Sampler which is in fact a Keyloadgen Sampler : 

![image](https://user-images.githubusercontent.com/5501911/131509381-e7a888be-4cd8-4117-a33c-50611ef48ccf.png)

**Comment by kszosze** [comment] 2021-09-02 08:14
Hi @M3lkior,

answering your question about plugin manager:

Developing a plugin under the scope of Plugin Manager is quite different from developing a normal plugin for JMeter. In the start of the project we consider following that path, but deadlines where so tight so we choose the basic one. But we still have this question over the table. Is an open discussion if we should move to this way of development.

Do you want collaborate with any thougths?

Cheers

**Comment by M3lkior** [comment] 2021-09-02 09:15
I think that provided your plugin into a PluginManager is not so important but provided your artifacts into a public Maven registry (without authentication) like Maven Central seems to be more important to avoid team rebuilding your project :)
Or if it is not possible, provided your version artifacts attached to the Github releases artifacts.

**Comment by kszosze** [comment] 2021-09-02 09:38
Well, this is something to discuss, since you can, generate 2 different artifacts from our code meaning that I need to set up a complex action (not too complex, really). 
Actually the Plugin jar is generated and uploaded into the Github Package like [this one](https://maven.pkg.github.com/corunet/kloadgen/net/coru/kloadgen/3.5.1/kloadgen-3.5.1-kloadgen-plugin-3.5.1.jar) , it has security I know, but was a temporary solutions previous my holidays leave. This is still a work in progres,

In a few days I'll return and will take a look to your suggestions.

**Comment by jemacineiras** [comment] 2022-06-01 06:44
Closing this because will be covered in #237

**Closed by jemacineiras** 2022-06-01 06:44 UTC
