### ISSUE TITLE
Failing to connect to Kafka

### ISSUE THREAD

**Issue by ShantiSumanth** [corunet/kloadgen#239] opened 2022-05-04 12:16 UTC
Hi, 
Trying to make a connection to Kafka and produce message(son) to a topic but failing to connect.

Whilst sending a message using JMeter below issues are seen
 Kafka producer is closing with timeout=0ms 
 Login module control flag not specified in JAAS config.

Please find the login specified in jaas.conf
<img width="868" alt="Screen Shot 2022-05-04 at 12 55 43" src="https://user-images.githubusercontent.com/94531655/166678234-264311e9-66b7-4596-920a-fb08895be109.png">

Have tried all the possible ways in defining the credentials in config file but didn't worked, would appreciate your help in sorting the issue?

Thanks

### KloadGen Version

Kloadgen-3.5.3

### Relevant log output

```shell
INFO o.a.k.c.p.KafkaProducer: [Producer clientId=perf-test] Closing the Kafka producer with timeoutMillis = 0 ms.
2022-04-28 11:04:20,547 INFO o.a.k.c.m.Metrics: Metrics scheduler closed
2022-04-28 11:04:20,547 INFO o.a.k.c.m.Metrics: Closing reporter org.apache.kafka.common.metrics.JmxReporter
2022-04-28 11:04:20,547 INFO o.a.k.c.m.Metrics: Metrics reporters closed
2022-04-28 11:04:20,547 INFO o.a.k.c.u.AppInfoParser: App info kafka.producer for perf-test unregistered
2022-04-28 11:04:20,548 ERROR o.a.j.p.j.s.AbstractJavaSamplerClient: Failed to construct kafka producer
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:440) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:291) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:318) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.setupTest(KafkaSchemaSampler.java:113) [kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Login module control flag not specified in JAAS config
	at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:110) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:63) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:88) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:82) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:167) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:448) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:429) ~[kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	... 10 more
2022-04-28 11:04:20,552 ERROR o.a.j.p.j.s.AbstractJavaSamplerClient: Failed to send message
java.lang.NullPointerException: Cannot invoke "org.apache.kafka.clients.producer.KafkaProducer.send(org.apache.kafka.clients.producer.ProducerRecord, org.apache.kafka.clients.producer.Callback)" because "this.producer" is null
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.runTest(KafkaSchemaSampler.java:153) [kloadgen-3.5.3-kloadgen-plugin-3.5.3.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) [ApacheJMeter_java.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2022-04-28 11:04:20,553 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group - KLoadgen 1-1
2022-04-28 11:04:20,553 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group - KLoadgen 1-1
2022-04-28 11:04:20,553 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2022-04-28 11:04:20,554 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

<img width="925" alt="Screen Shot 2022-05-04 at 13 17 38" src="https://user-images.githubusercontent.com/94531655/166680052-a2d1a1c3-7824-4d90-99a3-436216752fe5.png">
<img width="961" alt="Screen Shot 2022-05-04 at 13 18 04" src="https://user-images.githubusercontent.com/94531655/166680056-662470c9-27c4-4789-8a7e-357fa0b439f4.png">
<img width="828" alt="Screen Shot 2022-05-04 at 13 18 26" src="https://user-images.githubusercontent.com/94531655/166680057-8adb8eac-809a-4cb2-a096-d392671cb4f2.png">

**Comment by cmunozgomez** [comment] 2022-05-05 05:53
Hi @ShantiSumanth 

Thank you for your collaboration, we will review it and the changes/progress that we are making will inform you here.

**Comment by ShantiSumanth** [comment] 2022-05-05 08:22
Thanks @cmunozgomez.

**Comment by jgbriz** [comment] 2022-05-10 06:38
Hi @ShantiSumanth 

We are currently reviewing the issue. We'll inform you as soon as we get a solution.

**Comment by pedror19** [comment] 2022-05-10 09:09
Hi @ShantiSumanth 
We have problems reading the config from a jaas.conf file, try to set the kafka client auth from the jaas.conf file in the java.security.auth.login.config property of the java request. It must be a single line string like this:

KafkaClient { org.apache.kafka.common.security.plain.PlainLoginModule required username=(xxxx) password=(+dljlsjfl); };

**Comment by ShantiSumanth** [comment] 2022-05-11 09:47
Hi @pedror19, 

I've already included Kafka client auth in java request and added auth in a single line string but didn't work. 
![Screen Shot 2022-05-11 at 10 43 07](https://user-images.githubusercontent.com/94531655/167820744-b90e761c-794f-465d-9e89-4f89829ce0aa.png).

![Screen Shot 2022-05-11 at 10 46 05](https://user-images.githubusercontent.com/94531655/167820944-2e0e9f79-0e1a-45a5-9718-a6b91132c80e.png)

Please could you check if any other config is causing the issue.


Thanks

**Comment by pedror19** [comment] 2022-05-11 10:55
Hi @ShantiSumanth,

We will review the problem again and you will be in formed as soon as we made some improvement.

**Comment by pedror19** [comment] 2022-05-11 11:14
Hi again @ShantiSumanth,
We figured out that you are still using the jass.conf file, you need to write the config like this.

![imagen](https://user-images.githubusercontent.com/102519591/167836300-36286c13-3e98-4fc2-bc63-da9a2ab2def5.png)

**Comment by ShantiSumanth** [comment] 2022-05-11 12:30
Throwing java.io.ioexception
![Screen Shot 2022-05-11 at 13 28 43](https://user-images.githubusercontent.com/94531655/167850091-618469ed-8320-4da8-aab1-241c06b3dfaf.png)

**Comment by jgbriz** [comment] 2022-05-12 13:31
Hi @ShantiSumanth ,

We've noticed that you are using the 3.5.3 version of KLoadGen, can you update and use the lastest version? We will continue searching for the problem, but it'd be great if you can update so we can be sure the problem is not because of an old version.
One more thing, can you tell us where are you locating the jass.conf file?

**Comment by jemacineiras** [comment] 2022-05-12 14:18
Hi @ShantiSumanth,

we were playing around a bit with Kafka Authentication, and notice you need to pass the absolute path in the _java.security.auth.login.config_ property. It also works if you put the module configuration in a line like my colleague @pedror19 said, but, without the _KafkaClient_ part, neither the '_{_'.

Can you please try after update to the latest version (if possible)?

**Comment by pedror19** [comment] 2022-05-12 14:56
Hi @ShantiSumanth,
Adding to what @jemacineiras said you need to add to the _java.security.auth.login.config_ the serviceName field like this:

`org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="yourServiceName" username="(xxxxx)" password="(+dljlsjfl)";`

**Comment by ShantiSumanth** [comment] 2022-05-13 10:45
Thanks @pedror19 @jgbriz @jemacineiras .
I'm trying to get latest version of kloadgen plugin but failing to build the project. if possible would you mind providing me with latest version of kloadgen plugin please?

Thanks

**Comment by pedror19** [comment] 2022-05-13 10:58
Hi @ShantiSumanth,
Every version is deployed automatically to [maven central repository](https://search.maven.org/artifact/net.coru/kloadgen), you can download the latest version from there.

**Comment by ShantiSumanth** [comment] 2022-05-13 15:11
Thanks @pedror19.

Ran script with latest version but still failing with same error(java.io exception and login module control flag not specified). 

@jgbriz , jaas.conf file is located in jmeter/bin folder so given config file name directly in the request.
<img width="1026" alt="Screen Shot 2022-05-13 at 16 11 19" src="https://user-images.githubusercontent.com/94531655/168313676-f05d1725-038c-4a44-b1e3-5c75511c4e44.png">


Adding file name in java request is throwing error " java.lang.IllegalArgumentException: Login module control flag not specified in JAAS config"

giving authentication as a single string in the request is failing with exception, " java.io.IOException:org.apache.kafka.common.security.plain.PlainLoginModule required serviceName="yourServiceName" username="(xxxxx)" password="(+dljlsjfl)"; (No such file or directory)". 

<img width="954" alt="Screen Shot 2022-05-13 at 16 04 06" src="https://user-images.githubusercontent.com/94531655/168312616-5da2088f-dcdf-4a1d-88e7-0acf85780cf6.png">


Thanks

**Comment by jgbriz** [comment] 2022-05-16 07:59
Hello @ShantiSumanth ,
Thank you for the information, we'll look into it.

**Comment by pedror19** [comment] 2022-05-18 14:58
Hello @ShantiSumanth,

We have tested the connection and we had no problems adding to the _java.security.auth.login.config_ the absolute path of the jaas file and the connection string directly in that field as we said previously.

![test1](https://user-images.githubusercontent.com/102519591/169072782-3e5f9ca0-b71b-4da5-94f3-07e9f7815451.JPG)
![test2](https://user-images.githubusercontent.com/102519591/169072787-98fa8aea-82dc-4908-8c97-7bbe8bb5ca39.JPG)
![kafka-client](https://user-images.githubusercontent.com/102519591/169072788-b7a58700-a266-4c28-9e57-8ec9eb90983a.png)

**Comment by ShantiSumanth** [comment] 2022-05-23 10:13
Hi @pedror19, 

Any update on this please?

Thanks

**Comment by pedror19** [comment] 2022-05-23 10:23
Hello @ShantiSumanth,
Have you tested the configuration above?

**Comment by ShantiSumanth** [comment] 2022-05-24 19:20
Hi @pedror19 ,

Sorry missed updating. Don't see login module error but failing with java.lang.SecurityException: java.io.IOException: Configuration Error.

<img width="906" alt="Screen Shot 2022-05-24 at 20 16 05" src="https://user-images.githubusercontent.com/94531655/170115310-cc5e022f-2805-49df-9bcd-c0a3721d763d.png">
Could you please have a look at this, snapshot attached.

Thanks

**Comment by pedror19** [comment] 2022-05-25 13:32
Hello @ShantiSumanth 

We will look into it

**Comment by jgbriz** [comment] 2022-05-26 09:16
Hello @ShantiSumanth ,

Can you give us more detailed information regarding the error?, so we can dig more into the problem.

**Comment by jgbriz** [comment] 2022-06-01 06:55
Hello @ShantiSumanth ,
We need more information about the error you are getting, so we can have a better look trying to get the cause of the problem. If you can handle it, it will be appreciated.

**Comment by ShantiSumanth** [comment] 2022-06-07 09:45
Hi @jgbriz, 
Apologies, lost my project so building the script again. Will give detailed information on error by eod.

Thanks

**Comment by jgbriz** [comment] 2022-06-07 13:46
Hi @ShantiSumanth 
No problem. In that case, I think it's better option to close this issue, and to reopen one in case you have other problems.

**Comment by ShantiSumanth** [comment] 2022-06-08 09:53
Hi @jgbriz,
Experiencing two issues now, 
1. failing to open Value Schema File Load Generator config. fyi... Loaded json file (file content screenshot
<img width="349" alt="Screen Shot 2022-06-08 at 10 52 13" src="https://user-images.githubusercontent.com/94531655/172588117-3727c811-eafe-4430-95e1-444c065e113e.png">
 attached)
2. throwing java.io.IOException: Configuration Error, config error , think it is complaining about json file but the file is valid without errors. error details below,
Caused by: java.lang.SecurityException: java.io.IOException: Configuration Error:
	Line 14: expected [option key], found [null]
	at sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:139) ~[?:?]
	at sun.security.provider.ConfigFile.<init>(ConfigFile.java:104) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at javax.security.auth.login.Configuration$2.run(Configuration.java:258) ~[?:?]
	at javax.security.auth.login.Configuration$2.run(Configuration.java:249) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]

<img width="1035" alt="Screen Shot 2022-06-08 at 10 50 15" src="https://user-images.githubusercontent.com/94531655/172587628-26106b7b-71a4-4ed3-9bca-15e8ed6d7b68.png">

Please let me know if further details required for investigating.

Thanks

**Comment by jgbriz** [comment] 2022-06-08 10:33
Hi @ShantiSumanth ,
We'll look into it.

**Comment by jemacineiras** [comment] 2022-06-09 14:49
Hi @ShantiSumanth,

please, can you provide the required files in order to reproduce the error?
We are going to need the .jmx and .avsc ( or json schema) file you are using, or similar, in order to investigate and understand where is the problem.

Cheers

**Comment by ShantiSumanth** [comment] 2022-06-10 09:13
Hi @jemacineiras,
please find attached json and imx files
[jsonfile.json.zip](https://github.com/corunet/kloadgen/files/8877515/jsonfile.json.zip)
[CatalogueService-07June2022.jmx.zip](https://github.com/corunet/kloadgen/files/8877517/CatalogueService-07June2022.jmx.zip)
Thanks

**Comment by jemacineiras** [comment] 2022-06-13 08:54
Hi @ShantiSumanth,

those files are a bit confusing. What you want to achieve?
I need the original avsc file and the jmx, and you send to us a json file with values on it. This is not a data definition, as  the plugin requires. May be if you describe the test you want to build, we can help you better.

Cheers

**Comment by ShantiSumanth** [comment] 2022-06-14 10:00
Hi @jemacineiras,
I've changed all the confidential info to dummy values.
Trying to produce/send a json file(shared earlier) to Kafka topic in confluent cloud. With the current script I'm able to successfully connect to confluent cloud and load subjects, subject values were loaded using Value Schema Load gen config. 

Thanks

**Comment by jemacineiras** [comment] 2022-06-14 11:40
Hi @ShantiSumanth,

that is OK, but the json you send to us is not a valid [`json schema`](https://json-schema.org/) it looks like a Json with values. If you are trying to use this file as schema origin, it will not work.
If you try to use a data in JSON format, as source of the generation, we do not know what to generate, because there is no type and structure reference there.
Cheers!

**Comment by ShantiSumanth** [comment] 2022-06-16 08:42
Hi @jemacineiras,

Thanks for your support. Isn't the subject loaded on 'Value Schema Load Generator Config' type and structure reference? please correct me if I understood it wrongly.

Thanks
<img width="987" alt="Screen Shot 2022-06-16 at 09 37 41" src="https://user-images.githubusercontent.com/94531655/174030513-6a0c1b83-cc5f-44eb-b2a5-24c549a558f1.png">

**Comment by jemacineiras** [comment] 2022-06-16 08:56
Hi @ShantiSumanth,

that’s right, but I'm talking about the files you sent to us. We need more information about your test and the files in order to reproduce, unless you give us clearance to deal with your files in the confluent cloud.

Cheers.

**Comment by ShantiSumanth** [comment] 2022-06-20 08:21
Hi @jemacineiras,
PFA schema.

[schemaDoc.docx](https://github.com/corunet/kloadgen/files/8938848/schemaDoc.docx)

**Comment by jgbriz** [comment] 2022-06-23 08:16
Hi @ShantiSumanth,

We've made a solution to some problems we've detected processing the schema you provided us. Please, check the draft given in this issue, and try with that version.

Cheers.

**Comment by jgbriz** [comment] 2022-06-27 13:37
Hi @ShantiSumanth ,
You should be able to checkout the draft's branch. No permissions needed.

**Comment by jemacineiras** [comment] 2022-10-17 15:27
Hi, @ShantiSumanth,

have you tried what I said the last time? Any luck with your test?

Cheers

**Comment by dianaGomezGar** [comment] 2022-11-30 09:32
I'm going to close due to inactivity. If you have any question you can open a new Issue.

**Closed by dianaGomezGar** 2022-11-30 09:32 UTC
Labels: bug, question
