### ISSUE TITLE
Getting "ERROR o.a.j.r.ClassFinder: Error filtering class org.apache.kafka.common.requests.GroupCoordinatorResponse, it will be ignored java.lang.IncompatibleClassChangeError: class org.apache.kafka.common.requests.GroupCoordinatorResponse has interface org.apache.kafka.common.requests.AbstractRequestResponse as super class" Error When Jmeter is launched

### ISSUE THREAD

**Issue by gatlingtester** [corunet/kloadgen#187] opened 2022-02-23 09:56 UTC
I download code from repo and build it using maven as suggest in wiki page. Build was successful and JAR file was created. I copied the JAR file to Jmeter lib/ext folder and restarted Jmeter (version 5.3).

I am getting below error on launching of Jmeter. Also non of the kafka config elements are getting displayed.
2022-02-22 16:30:20,913 ERROR o.a.j.r.ClassFinder: Error filtering class org.apache.kafka.common.requests.GroupCoordinatorResponse, it will be ignored
java.lang.IncompatibleClassChangeError: class org.apache.kafka.common.requests.GroupCoordinatorResponse has interface org.apache.kafka.common.requests.AbstractRequestResponse as super class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_251]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_251]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.isChildOf(ClassFinder.java:102) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.accept(ClassFinder.java:88) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.applyFiltering(ClassFinder.java:438) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:398) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:328) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:301) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:233) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:215) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:184) ~[jorphan.jar:5.3]
	at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:128) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:107) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:94) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:184) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_251]
2022-02-22 16:30:20,915 ERROR o.a.j.r.ClassFinder: Error filtering class org.apache.kafka.common.requests.ListOffsetResponse, it will be ignored
java.lang.IncompatibleClassChangeError: class org.apache.kafka.common.requests.ListOffsetResponse has interface org.apache.kafka.common.requests.AbstractRequestResponse as super class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_251]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_251]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_251]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_251]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.isChildOf(ClassFinder.java:102) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.accept(ClassFinder.java:88) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.applyFiltering(ClassFinder.java:438) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:398) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:328) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:301) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:233) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:215) ~[jorphan.jar:5.3]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:184) ~[jorphan.jar:5.3]
	at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:128) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:107) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:94) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:184) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:46) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_251]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_251]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_251]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_251]
![image](https://user-images.githubusercontent.com/74158458/155296701-2506ab5c-4941-4b4e-8ca2-308b177068fd.png)

**Comment by fcampostato** [comment] 2022-02-23 12:50
Hi @gatlingtester,

Thank you for using the plugin.

I've been looking your error but I'm not able to reproduce it. It seems that may be caused by an unupdated component. 
Do you think you could try to update to a newer version of JMeter (5.4+)?

If after updating it, the error is still there, came back and we will try to help.

Cheers!

**Comment by fcampostato** [comment] 2022-03-08 08:24
Hi @gatlingtester,

Are there any news about this? If it isn't, I will close this issue in the next days.
If you have problems later on, please feel free to open a new issue and we will try to help you.

Cheers!

**Comment by fcampostato** [comment] 2022-03-11 08:57
Hi @gatlingtester,

Due to the innactivity related with this issue, I'm going to close it.

If you have problems in the future, please feel free to come back and we will try to help you.

Cheers!

**Closed by fcampostato** 2022-03-11 08:57 UTC
