### ISSUE TITLE
Kafka file load generator config element is missing from the config element list

### ISSUE THREAD

**Issue by Chaderbura** [corunet/kloadgen#79] opened 2021-01-10 07:17 UTC
Hi,

thanks for building this wonderful plugin. I have successfully built this plugin with no error and able to use it in my jmeter. I am using java 11 to build the plugin. 

But I am missing a config element which kafka file load generator config in my config element list. I tried different build and java configurations but still its missing. I dont know what i am doing wrong as it gives no error. I downloaded the latest kloadgen release. 

Please help me to build it correctly so that i can use the Kafka file load generator config element. 
![kafka bug](https://user-images.githubusercontent.com/21003619/104116808-2942ec80-5346-11eb-8f32-5c3056b6fe5f.png)

**Comment by kszosze** [comment] 2021-01-10 08:55
Hi @Chaderbura,

Seeing your screenshot I'm seeing you are nos using the latest one, but a previous release. In that case you are looking for the "Schema File Load Generator Config" just down in the list. 
The Kafka File Load Generator, split in two in latest commit to:
- Value Schema File Load Generator Config
- Key Schema File Load Generator Config
Depends if you are referring an event Value or an event Key.
That's in the latest 3.0.0 Release the current one.

I'll recommend you to update to the last version, but carefully, there has been a rework and previous jmx files will no open correctly.

Please try and let us know.

Cheers!!

**Comment by rite2keshav** [comment] 2021-01-10 17:44
I am using version 3.2 but still not getting the 'Kafka load generator config' element,

![image](https://user-images.githubusercontent.com/36656062/104130933-8025e180-5399-11eb-8e18-4d08f73fe722.png)

**Comment by kszosze** [comment] 2021-01-10 18:10
Hi @rite2keshav ,
that is because there is not more Kafka Load Generator Config. has been renamed as Value Schema Load Generator Config, just the last one in the list.

Cheers!

**Comment by rite2keshav** [comment] 2021-01-11 04:32
Is there something wrong, I am not able to add 'Value Subject Name' in 'Value Schema Load Generator Config'. It is not allowing me to write anything in the text box. Can not paste even. Is it a known issue ?

**Comment by kszosze** [comment] 2021-01-11 07:40
Hi @rite2keshav,
let´s review the path.... the "Value Schema Load Generator Config" depends of the "Schema Registry Config Element" which define the comunication with the schema registry holding the AVRO files. Once this last component is configure and test (just throught the button) the list of schemas will be donwloaded and will populate the combo box in the "Value Schema Load Generator Config" this combo box is an autocomplete one, so will help you to choose the schema to work with.
The "Value Schema File Load Generator Config" doesn´t depend on an external Schema Registry, just use the file you provide to generate the load.
That help you?
Cheers!!

**Comment by rite2keshav** [comment] 2021-01-11 08:44
Thanks @kszosze 
Able to do it now, but got stuck here.. Could you please help,
2021-01-11 14:13:03,290 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'KP00_03_Java Request'.
net.coru.kloadgen.exception.KLoadGenException: Something Odd just happened
	at net.coru.kloadgen.processor.AvroSchemaProcessor.createObject(AvroSchemaProcessor.java:123) ~[kloadgen-3.2.0.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.createObjectArray(AvroSchemaProcessor.java:198) ~[kloadgen-3.2.0.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.createArray(AvroSchemaProcessor.java:178) ~[kloadgen-3.2.0.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.createObject(AvroSchemaProcessor.java:150) ~[kloadgen-3.2.0.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.next(AvroSchemaProcessor.java:96) ~[kloadgen-3.2.0.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.nextMessage(AvroLoadGenerator.java:60) ~[kloadgen-3.2.0.jar:?]
	at net.coru.kloadgen.sampler.AbstractKafkaSampler.runTest(AbstractKafkaSampler.java:84) ~[kloadgen-3.2.0.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:635) ~[ApacheJMeter_core.jar:5.4]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4]
	at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by kszosze** [comment] 2021-01-11 09:32
Hi @rite2keshav,
That´s an odd error... something unexpected happen. Can you share the avro schema you are using so we can reproducte it (or a similar one with same structure if you cannot share data.)

Cheers!!

**Comment by kszosze** [comment] 2021-01-13 07:40
Hi @Chaderbura,
I still need a sample of your schema. That error happened trying to generate the payload due some inconsistence in it. 
Can you please send me file with the same structure? field names are not important, but avro sctructure it is.
Cheers

**Comment by jemacineiras** [comment] 2021-01-19 08:02
After a week without answer we close this issue.

**Closed by jemacineiras** 2021-01-19 08:02 UTC
