### ISSUE TITLE
Unable to add Value Schema Load Generator config.

### ISSUE THREAD

**Issue by sushmatshetty** [corunet/kloadgen#186] opened 2022-02-17 22:39 UTC
2022-02-17 14:39:34,165 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.Error: java.lang.reflect.InvocationTargetException
	at org.apache.jmeter.testbeans.gui.GenericTestBeanCustomizer.<init>(GenericTestBeanCustomizer.java:250) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.testbeans.gui.TestBeanGUI.init(TestBeanGUI.java:425) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.testbeans.gui.TestBeanGUI.configure(TestBeanGUI.java:301) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addComponent(JMeterTreeModel.java:162) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.gui.action.AddToTree.doAction(AddToTree.java:69) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.4.3]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:741) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]

**Comment by sushmatshetty** [comment] 2022-02-17 22:59
Sushma_Test.jm
[Sushma_Test.jmx.zip](https://github.com/corunet/kloadgen/files/8092773/Sushma_Test.jmx.zip)
x

**Comment by kszosze** [comment] 2022-02-17 23:22
HI @sushmatshetty,

I can open your jmx without no problem after removing that KafkaProducerSampler `com.di.jmeter.kafka.sampler.KafkaProducerSampler`. My guessing is you are dealing with some jar clash. What other plugins are you using, so I can try to reproduce the conflict?

Cheers!

**Comment by sushmatshetty** [comment] 2022-02-18 00:41
Thankyou.
I dont have any other plugins. I had pepper box , but I have removed the jar file.
![image](https://user-images.githubusercontent.com/92820421/154595637-b852a1ff-4c81-48e3-a59f-576ee36893d9.png)

**Comment by sushmatshetty** [comment] 2022-02-18 00:41
![image](https://user-images.githubusercontent.com/92820421/154595690-ec6fbf1a-11c8-47e3-ae41-289c578cd8ae.png)

**Comment by cmunozgomez** [comment] 2022-02-18 12:08
Hi, I have the issue assigned. 
Sorry for the inconvenience for not having answered before, we will have it as soon as possible.

**Comment by cmunozgomez** [comment] 2022-02-22 11:42
Hi @sushmatshetty 

I have finally managed to reproduce the error with the environment that you have installed in JMeter.

You have previously commented that you have no more plugins installed, but to simulate the error with the test-plan that you have sent us, I have been forced to install the following 3: di-kafkameter, kafkameter y jmeter.backendlistener.kafka.

If I don't install these plugins, the test-plan fails to load in Jmeter. In fact Jmeter Plugin Manager recommends me to install them.

The kloadgen-plugin had already embedded all the necessary classes and jars in order to produce and consume messages. Adding yours jar's probably you are overwriting the ones we are adding.

Why you need that jar included?

**Comment by sushmatshetty** [comment] 2022-02-22 17:18
![image](https://user-images.githubusercontent.com/92820421/155183992-a2d456d2-5c0f-4671-88e4-4d4020b105db.png)

I removed and ran the test. this is the failure . Is this something related to my inputs?

**Comment by cmunozgomez** [comment] 2022-02-23 09:22
Hi @sushmatshetty

I suppose that you have finally been able to add a Value Schema Load Generator config to your test plan. Removing the plugins that I mentioned in my previous answer does not give problems to add it.

About the problem that appears in the new image capture that you have added (which I suppose corresponds to the execution of the test) I do not know what new changes you have made in the test plan.

Is it possible you send it again or explain me what changes you have made so that I can simulate it? if you can attach the AVRO and the changed Test Plan in order to be able to reproduce that error, i'll appreciate it.

**Comment by sushmatshetty** [comment] 2022-02-23 16:37
hi,
Yes I am able to add the Value schema File Load Generator now. when I run the test this is the error:
![Screen Shot 2022-02-23 at 8 35 29 AM](https://user-images.githubusercontent.com/92820421/155364241-bbaff561-7be3-4c6e-8c99-cf0a7610ae7e.png)

 I will send the test plan and Avro.

thanks.

**Comment by sushmatshetty** [comment] 2022-02-23 20:11
[debug_1.jmx.zip](https://github.com/corunet/kloadgen/files/8127518/debug_1.jmx.zip)

attached is the test plan. Please check and let me know where I am going wrong.

**Comment by cmunozgomez** [comment] 2022-02-24 11:14
Hi @sushmatshetty

I have used the test plan that you have sent me (debug_1.jmx) and in that test plan you simultaneously use
a Value Schema File Load Generator Config and a Value Schema Load Generator Config. You should try only one at a time so that you can better see the errors.

In the case of using Value Schema File Load Generator Config in the test, no schema is loaded and it gives me your error. The error is produced because the serializer, because it is not possible to access a schema. When I load an Avro schema it worked fine.

**Comment by sushmatshetty** [comment] 2022-02-24 22:31
That was very useful. I used the Value Schema Load Generator. I added all the values from the schema.
![Screen Shot 2022-02-24 at 2 26 14 PM](https://user-images.githubusercontent.com/92820421/155618051-0a78dc71-5690-4f35-a471-181c159f3ab9.png)

our env has jaas enabled. so I gave the conf file path. But I am getting below error:
![image](https://user-images.githubusercontent.com/92820421/155618271-bc90c01f-0936-467d-bb25-819a715db516.png)

Also this is how the conf file looks like.

KafkaClient {
org.apache.kafka.common.security.plain.PlainLoginModule required
username="username"
password="password"
};


can you please let me know what is missing here?

**Comment by cmunozgomez** [comment] 2022-02-25 11:46
Hi @sushmatshetty

Apparently the conf file for authentication via sasl is correct, as it appears in the comment.

It is possible that the problem is in the configuration of values ​​in the Kafka Producer Properties. I add the following url to the official documentation https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_plain.html#configuration
 that may help you change certain values ​​because I have seen them different from the official configuration in the examples you have sent me.

If after applying the changes indicated in the official documentation it still doesn't work for you, send me the configuration in the Kafka Producer Properties that you are using so that I can try to see what the problem is.

**Comment by sushmatshetty** [comment] 2022-02-28 19:02
![Screen Shot 2022-02-28 at 11 00 18 AM](https://user-images.githubusercontent.com/92820421/156042605-cdfdd216-888a-437a-9578-90ac62a26b81.png)
I have put in all the details as given by my dev team. It still fails with 

022-02-28 10:58:51,727 INFO o.a.k.c.u.AppInfoParser: App info kafka.producer for  unregistered
2022-02-28 10:58:51,727 ERROR o.a.j.p.j.s.AbstractJavaSamplerClient: Failed to construct kafka producer
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:440) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:291) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:318) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.setupTest(KafkaSchemaSampler.java:112) [kloadgen-3.8.2-plugin.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.SecurityException: java.io.IOException: Configuration Error:
	Line 5: expected [option key]


Can u see if this is something u have come across.
thank u

**Comment by cmunozgomez** [comment] 2022-03-01 07:16
Hi @sushmatshetty

the error that you indicate to me seems to come from the following cause: _**Caused by: java.lang.SecurityException: java.io.IOException: Configuration Error: Line 5: expected [option key]**_ As stated in the error message itself.

I think that this error usually occurs when it does not read the properties of the jass.conf file correctly, please check that it is well written, for example in the case you sent me:

KafkaClient {
org.apache.kafka.common.security.plain.PlainLoginModule required
username="username"
password="password"
};

It seems that you are missing a semicolon after the 'password="password"', you can see the example that I put below so that you can see how it would be.

KafkaClient {
org.apache.kafka.common.security.plain.PlainLoginModule required
username="username"
password="password";
};

Please check that what I indicate is correct, change it if necessary and try again, while I will review the configuration that you indicate me in the last answer.

**Comment by sushmatshetty** [comment] 2022-03-01 16:14
Hi, Yes that worked fine. I have one question. In the Value Schema Load Generator Config, is it necessary to add the "Field Length"?

Please check below error:

2022-03-01 08:10:51,639 ERROR n.c.k.l.i.AvroLoadGenerator: Please make sure that properties data type and expression function return type are compatible with each other
java.net.UnknownHostException: avroregistry.octanner.io
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:272) ~[kloadgen-3.8.2-plugin.jar:?]
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:351) ~[kloadgen-3.8.2-plugin.jar:?]
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:716) ~[kloadgen-3.8.2-plugin.jar:?]
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:707) ~[kloadgen-3.8.2-plugin.jar:?]
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getLatestSchemaMetadata(CachedSchemaRegistryClient.java:332) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.getSchemaBySubject(AvroLoadGenerator.java:69) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.retrieveSchema(AvroLoadGenerator.java:65) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.setUpGenerator(AvroLoadGenerator.java:42) [kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.sampler.SamplerUtil.configureValueGenerator(SamplerUtil.java:402) [kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.setupTest(KafkaSchemaSampler.java:92) [kloadgen-3.8.2-plugin.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2022-03-01 08:10:51,645 ERROR n.c.k.l.i.AvroLoadGenerator: Please make sure that properties data type and expression function return type are compatible with each other
java.lang.NullPointerException: Cannot invoke "String.length()" because "content" is null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1045) ~[jackson-core-2.10.5.jar:2.10.5]
	at org.apache.avro.Schema$Parser.parse(Schema.java:1413) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.setUpGenerator(AvroLoadGenerator.java:52) [kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.sampler.SamplerUtil.configureValueGenerator(SamplerUtil.java:408) [kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.setupTest(KafkaSchemaSampler.java:92) [kloadgen-3.8.2-plugin.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by sushmatshetty** [comment] 2022-03-01 17:17
=====I gnore the above one. Below is the error

2022-03-01 09:15:29,253 INFO o.a.k.c.u.AppInfoParser: App info kafka.producer for  unregistered
2022-03-01 09:15:29,253 ERROR o.a.j.p.j.s.AbstractJavaSamplerClient: Failed to construct kafka producer
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:440) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:291) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:318) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.setupTest(KafkaSchemaSampler.java:112) [kloadgen-3.8.2-plugin.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore <Keystore Location> of type JKS
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:184) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:448) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:429) ~[kloadgen-3.8.2-plugin.jar:?]
	... 10 more
Caused by: org.apache.kafka.common.KafkaException: Failed to load SSL keystore <Keystore Location> of type JKS
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.load(DefaultSslEngineFactory.java:377) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.<init>(DefaultSslEngineFactory.java:349) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createKeystore(DefaultSslEngineFactory.java:299) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.configure(DefaultSslEngineFactory.java:161) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.security.ssl.SslFactory.instantiateSslEngineFactory(SslFactory.java:138) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:95) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:180) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:448) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:429) ~[kloadgen-3.8.2-plugin.jar:?]
	... 10 more
Caused by: java.nio.file.NoSuchFileException: <Keystore Location>
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.load(DefaultSslEngineFactory.java:370) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$FileBasedStore.<init>(DefaultSslEngineFactory.java:349) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createKeystore(DefaultSslEngineFactory.java:299) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.configure(DefaultSslEngineFactory.java:161) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.security.ssl.SslFactory.instantiateSslEngineFactory(SslFactory.java:138) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:95) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:180) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:448) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:429) ~[kloadgen-3.8.2-plugin.jar:?]
	... 10 more
2022-03-01 09:15:29,253 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer Properties'.
java.lang.IllegalArgumentException: Invalid UUID string:

**Comment by sushmatshetty** [comment] 2022-03-01 23:42
I was able to get the right UUID. But still I get this error: 2022-03-01 15:35:57,861 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer'.
java.lang.IllegalArgumentException: UUID string too large
	at java.util.UUID.fromString1(UUID.java:264) ~[?:?]
	at java.util.UUID.fromString(UUID.java:258) ~[?:?]

Thanks

**Comment by cmunozgomez** [comment] 2022-03-02 06:28
Hi @sushmatshetty

This UUID error usually occurs because you may be putting a UUID without dashes (example: "0177f035e51c4a468b825b157371c2a5" when it should be "0177f035-e51c-4a46-8b82-5b157371c2a5" ).

Please you try again with a correct UUID and containing hyphens to see if it works correctly.

**Comment by cmunozgomez** [comment] 2022-03-02 14:41
Hi @sushmatshetty

I wanted to tell you that the last errors are not related to the plugin itself, they are JMeter configuration errors, definition of variables in files, etc.

Therefore, if the objective of opening the issue has been solved, it would be necessary to close it and if you have any other error, you can open a new one with the new problem.

We are happy to help if possible but we don't usually support all JMeter issues only plugin related ones.

So I await your response to the solution of the problem with the UUID and if there are still problems with the plugin or not, to act according to what I have told you.

**Comment by sushmatshetty** [comment] 2022-03-02 16:39
Hi,
I tried both with and without the dashes, either it says the UUID is too long or its invalid.
Yes if its not related to the pligin we can go ahead and close the ticket. thank you for the support.

022-03-02 08:35:32,889 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer'.
java.lang.IllegalArgumentException: Invalid UUID string: "UUID withput dashes"
	at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
	at java.util.UUID.fromString(UUID.java:258) ~[?:?]
	at net.coru.kloadgen.randomtool.random.RandomObject.getUUIDValueOrRandom(RandomObject.java:256) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.randomtool.random.RandomObject.generateRandom(RandomObject.java:142) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.randomtool.generator.AvroGeneratorTool.generateObject(AvroGeneratorTool.java:73) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.processor.AvroSchemaProcessor.next(AvroSchemaProcessor.java:132) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.loadgen.impl.AvroLoadGenerator.nextMessage(AvroLoadGenerator.java:60) ~[kloadgen-3.8.2-plugin.jar:?]
	at net.coru.kloadgen.sampler.KafkaSchemaSampler.runTest(KafkaSchemaSampler.java:137) ~[kloadgen-3.8.2-plugin.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by cmunozgomez** [comment] 2022-03-03 09:04
Hi @sushmatshetty

We are going to close the current issue and please open a new one with the current error.

For this new error, when you open the issue, attach us the updated test plan that you are using and an example of a uuid that you are using. You also indicate which version of JVM and JDK you are using.

Thank you very much and as soon as you open the new issue we will start working again, I hope we have been able to help you with the initial problems and those that have been appearing in this issue.

**Closed by cmunozgomez** 2022-03-03 09:04 UTC
