### ISSUE TITLE
Build Issue. Unable to generate Jar as mentioned in read me.

### ISSUE THREAD

**Issue by saini26rohit** [corunet/kloadgen#98] opened 2021-05-07 04:17 UTC
Hi Team,
I have requirement to test kafka with avro schema message for which I came across your plugin. I tried to create the jar with the steps mentiond in the Build Project section. But I get dependency issues. Below is the output. I tried with eclipse and with maven both but every time build fails.
I have tried with master branch and with release-3.0.0 branch. but every time it gives dependency issues.
Is it possible to provide the JAR directly or will be possible to provide more detailed steps to use this with versions of tool and all. I have added manually some 20-30 but still it gives more... I am using home computer so to clarify I am not running this behind any proxy. 

Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/39/commons-parent-39.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/50/commons-parent-50.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/48/commons-parent-48.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/github/luben/zstd-jni/1.4.4-7/zstd-jni-1.4.4-7.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/lz4/lz4-java/1.7.1/lz4-java-1.7.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.10.2/jackson-databind-2.10.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.13/2.10.2/jackson-module-scala_2.13-2.10.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.10.2/jackson-dataformat-csv-2.10.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.10.2/jackson-datatype-jdk8-2.10.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.1.6/scala-collection-compat_2.13-2.1.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/scala-lang/modules/scala-java8-compat_2.13/0.9.1/scala-java8-compat_2.13-0.9.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.13.2/scala-library-2.13.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/scala-lang/scala-reflect/2.13.2/scala-reflect-2.13.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/typesafe/scala-logging/scala-logging_2.13/3.9.2/scala-logging_2.13-3.9.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/zookeeper/zookeeper/3.5.8/zookeeper-3.5.8.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/google/guava/guava-parent/30.0-jre/guava-parent-30.0-jre.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/avro/avro-parent/1.10.0/avro-parent-1.10.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-base/2.10.5/jackson-base-2.10.5.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/51/commons-parent-51.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/eclipse/ee4j/project/1.0.5/project-1.0.5.pom
Downloading from confluent: https://packages.confluent.io/maven/org/eclipse/ee4j/project/1.0.5/project-1.0.5.pom
Downloading from jitpack.io: https://jitpack.io/org/eclipse/ee4j/project/1.0.5/project-1.0.5.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-parent/2.10/jackson-parent-2.10.pom
Downloading from confluent: https://packages.confluent.io/maven/com/fasterxml/jackson/jackson-parent/2.10/jackson-parent-2.10.pom
Downloading from jitpack.io: https://jitpack.io/com/fasterxml/jackson/jackson-parent/2.10/jackson-parent-2.10.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/2.0.0-alpha1/slf4j-parent-2.0.0-alpha1.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-commons/1.5.2/junit-platform-commons-1.5.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/assertj/assertj-parent-pom/2.2.8/assertj-parent-pom-2.2.8.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.6.3/jackson-core-2.6.3.pom
Downloading from central: https://repo.maven.apache.org/maven2/net/minidev/json-smart/2.3/json-smart-2.3.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.6.3/jackson-databind-2.6.3.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/assertj/assertj-core/3.8.0/assertj-core-3.8.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/mockito/mockito-core/3.6.0/mockito-core-3.6.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/mockito/mockito-junit-jupiter/3.6.0/mockito-junit-jupiter-3.6.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/github/tomakehurst/wiremock/2.27.2/wiremock-2.27.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/ru/lanwen/wiremock/wiremock-junit5/1.3.1/wiremock-junit5-1.3.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/io/rest-assured/rest-assured/4.3.2/rest-assured-4.3.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-params/5.5.2/junit-jupiter-params-5.5.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.5.2/junit-jupiter-engine-5.5.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/jmeter/ApacheJMeter_java/5.3/ApacheJMeter_java-5.3.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-jdk14/2.0.0-alpha1/slf4j-jdk14-2.0.0-alpha1.pom

It will be great help you there can be any assistance on this.

**Comment by kszosze** [comment] 2021-05-07 07:06
HI @saini26rohit ,
you should not need to add any dependency for the build. Can you please provide a full log of the fail?
It will help if you can share with us which JVM and maven version are you using for it.
Regards!

**Comment by saini26rohit** [comment] 2021-05-07 09:32
Thank you @kszosze, for the prompt response. I was acting naive. I managed to get the Jar files now. I had to upgrade to JDK 16 and I used eclipse version 2021-03. Post that it downloaded all the dependencies and worked. However, on first time build it failed with error: "_Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test_" . On this I made changes to POM --> "<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.19.1</version>
    <configuration>
        **<testFailureIgnore>true</testFailureIgnore>**
    </configuration>
</plugin"

And did a compelte clean install. It worked and generated the Jars under target folder: 
1) kloadgen-3.0.0.jar
2) kloadgen-plugin-3.0.0.jar.

I have JMeter (5.0.r1840935). I copied the kloadgen-plugin-3.0.0.jar under /lib/ext folder of JMeter. 
**No, I do not see following in my JMeter :
1) KLoadGen Kafka Sampler 
	ConfluentKafkaSampler 
	Generic Kafka Sampler 
	Generic Binary Kafka Sampler
2) Value Serialized Config 
3) Value File Serialized Config
4) Schema Registry Config
5) Key Serialized Config
6) Key File Serialized Config**

![Generated Jar](https://user-images.githubusercontent.com/83584135/117429536-c7d20980-af44-11eb-8215-03107c8d083b.jpg)
![4ElementsOnly](https://user-images.githubusercontent.com/83584135/117429544-c99bcd00-af44-11eb-8280-d93057dcf8df.jpg)
![Config Elements](https://user-images.githubusercontent.com/83584135/117429547-c99bcd00-af44-11eb-83c7-4400ed29f29e.jpg)
![Sampler](https://user-images.githubusercontent.com/83584135/117429570-d0c2db00-af44-11eb-894d-d6e636cd58f4.jpg)
![Jar_Added_in_Lib_Of_Jmeter](https://user-images.githubusercontent.com/83584135/117429929-28f9dd00-af45-11eb-93aa-5bae041d6e9d.jpg)

Thanks,

**Comment by kszosze** [comment] 2021-05-09 07:37
HI @saini26rohit,
I´m curious about which version of the code are you actually using.
Master and Release 3.0.0 are using both version 2.22.2 of Surefire Plugin.
Regarding Java 16, still not supported for us. There is an issue between the version of Lombok and Java 16, so we need to update it in order to make work.
Can you provide a fork of kloadgen with your changes so I can download that code and testing?
I cannot reproduce your situation with the current master, neither release 3.0.0.
Cheers!!

**Comment by saini26rohit** [comment] 2021-05-12 04:39
@kszosze 
I tried with both Master and Release 3.0.0 and for both build fail with error: "Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test". 
Both Master and Release 3.0.0 are using version 2.22.2 for Surefire Plugin. So I was not sure what to do. I googled and the solution was to add testFailureIgnore tag in POM.xml.
<configuration>
        <testFailureIgnore>true</testFailureIgnore>
</configuration>
 
In my previous comment you might see version : 2.19.1. This was from google search. My intention was to tell you that I added testFailureIgnore tag to POM.xml

**Comment by kszosze** [comment] 2021-05-15 08:47
Hi @saini26rohit 
Sorry for late reply, I have a branch for this issue. Can you try to build it?
Regards

**Comment by saini26rohit** [comment] 2021-05-16 07:47
Hi @kszosze
Thank you for the help. I will try to build with the branch and update you. Mean while can you help me do identify what I am doing wrong below:  
When I try in my corporate machine behind corporate network where I have Jdk1.8 I am getting below error:
/PathInMachine/Kloadgen-master/src/main/java/net/coru/kloadgen/extractor/extractors/AvroExtractor.java:[144,21] Valid_TYPES has protected in net.coru.kloadgen.util.RandomTool
/PathInMachine/Kloadgen-master/src/main/java/net/coru/kloadgen/property/editoir/ValueSerializerPropertyEditor.java[104,52] cannot find symbol
symbol : method requireNonNullElse(java.lang.Object,int)
location: class java.util.Objects

Can you help me understand what I am doing wrong.

**Comment by kszosze** [comment] 2021-05-17 20:09
Hi @saini26rohit ,

This is a know issue fixed in the branch I'm just made to investigate your case.
Can you please use it to build?

Cheers!

**Closed** 2021-05-28 16:04 UTC
Labels: help wanted
